# Posix Makefile for RunCPM

PROG = RunCPM

MFILE = Makefile.posix

# Are we including the extended debugger ??
#extendedDebug = TRUE

# Compiler command
CC ?= gcc

# Flags to pass to the compiler
CFLAGS ?= -Wall -O3 -fPIC -Wno-unused-variable

DEBUG_MODE :=

ifeq ($(DEBUG),1)
DEBUG_MODE := 1
endif

ifneq ($(findstring -DDEBUG=1,$(CFLAGS)),)
DEBUG_MODE := 1
endif

ifeq ($(DEBUG_MODE),1)
CFLAGS := $(filter-out -O%,$(CFLAGS))
CFLAGS := -Wall -O0 -fPIC -Wno-unused-variable -g -g -DDEBUG=1 -DDEBUGLOG=1 $(CFLAGS)
endif

# CCP selection: define one CCP macro when invoking make to select the CCP
# Example: `make posix CCP=DR build`
ifdef CCP
CFLAGS += -DCCP_$(CCP)
endif

# CPU selection: define `CPU` to the header filename to include, e.g. cpu1.h
# Example: `make posix CPU=cpu2.h build`
ifdef CPU
CFLAGS += -DCPU=\"$(CPU).h\"
endif

# Enable CPM3 extension
# Example: `make posix CPM3=1`
ifdef CPM3
CFLAGS += -DCPM3
endif

# Flags to pass to the linker
LDFLAGS =

# Objects to build
OBJS = main.o 

ifdef streamIO
CFLAGS += -DSTREAMIO
endif

## extended debugger adds a bunch more object files, glib library & conditional compile flags 
##     to enable multiple breakpoints, memory watchpoints and variables in the on-board debugger (Ctl-D)
##     as well as enabling GDB remote debugging if debug port is given on the commandline.
ifdef extendedDebug

CFLAGS += -DDEBUG -DEXTENDED_DEBUG $$(pkg-config --cflags glib-2.0)
LDFLAGS+= $$(pkg-config --libs glib-2.0)

OBJS += debugger/debugger.o debugger/breakpoint.o debugger/expression.o debugger/ui.o \
	debugger/gdbserver.o debugger/packets.o debugger/gdbserver_utils.o \
	debugger/disassemble.o debugger/variable.o debugger/system_variable.o debugger/z80_variables.o \
	debugger/command.o debugger/commandy.o debugger/commandl.o debugger/completer.o isocline/isocline.o
endif

# Clean up program
RM = rm -f

#------------------------------------------------------------------------

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) $(OBJS) -o $(PROG) $(LDFLAGS) $(LIBS)

rebuild: clean all

%.o: %.c
	$(CC) $(CFLAGS) $(GLIB_CFLAGS) -c -o $@ $<

## extended debugger uses bison and lex
ifdef extendedDebug
%.c: %.y
	$(SHELL) ./debugger/ylwrap $< y.tab.c $@ y.tab.h $*.h y.output $*.output -- bison -y -d

%.c: %.l
	$(SHELL) ./debugger/ylwrap $< lex.yy.c $@ -- flex
endif

.PHONY: clean
clean:
	$(RM) *.o
	$(RM) $(PROG)
ifdef extendedDebug
	$(RM) debugger/*.o debugger/command[ly].[ch] isocline/*.o
endif
